---
- hosts: localhost
  tasks:
    - name: Pull Docker image from Docker Hub
      shell: docker pull shamik99/shamik-repo

    - name: Run Docker container
      shell: docker run -d -p 8081:8080 shamik99/shamik-repo